name: Build and Release (Windows)

on:
  push:
    tags:
      - 'v*'
      
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile ding.py --name=ding

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install WiX Toolset
        run: |
          choco install wixtoolset --version=3.11.2 -y
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
        shell: cmd

      - name: Prepare WiX assets
        run: |
          if not exist dist\ding.ico (
            copy NUL dist\ding.ico
          )
          echo " Ding Command Line Tool | MIT License" > license.rtf
        shell: cmd

      - name: Show directory structure
        run: tree /f
        shell: cmd

      - name: Build MSI with WiX
        run: |
          candle.exe -dVersion=${{ env.VERSION }} -dSourcePath=dist -out dist\ ding.wxs -v
          light.exe -ext WixUIExtension -ext WixUtilExtension -b dist -out dist\ding_${{ env.VERSION }}.msi dist\ding.wixobj -v
        shell: cmd

      - name: List dist directory contents
        run: dir dist
        shell: cmd

      - name: Rename EXE
        run: move dist\ding.exe dist\ding-${{ env.VERSION }}-windows.exe
        shell: cmd

      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ding-${{ env.VERSION }}-windows.exe
            dist/ding_${{ env.VERSION }}.msi
        env:
          GITHUB_TOKEN: ${{ secrets.DINGTOKEN }}